ALTER TABLE "Order"
  ADD COLUMN "vendorComment" TEXT;

CREATE TABLE "OrderTracking" (
  "id" TEXT PRIMARY KEY,
  "orderId" TEXT NOT NULL,
  "courierId" TEXT NOT NULL,
  "lat" DOUBLE PRECISION NOT NULL,
  "lng" DOUBLE PRECISION NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "OrderTracking_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
